

local sys=require("wetgenes.aelua.sys")
local user=require("wetgenes.aelua.user")

local wet_html=require("wetgenes.html")

local string=string
local math=math

module("html")

-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
header=function(d)

	return wet_html.replace([[
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
 <head>
<title>{title}</title>

<link REL="SHORTCUT ICON" HREF="/favicon.ico">

<link rel="stylesheet" type="text/css" href="/css/jnice.css" /> 
<link rel="stylesheet" type="text/css" href="/css/aelua.css" /> 

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js"></script>
<script type="text/javascript" src="/js/jquery.jnice.js"></script>


 </head>
<body>
<div class="aelua_base">
]],d)

end

-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
footer=function(d)

	if not d.time then
		d.time=math.ceil((sys.clock()-d.srv.clock_start)*1000)/1000
	end

	d.report="Generated by <a href=\"http://code.google.com/p/aelua/\">aelua</a> in "..(d.time or 0).." Seconds."
		
	return wet_html.replace([[
<div class="aelua_foot_data">
<br/>
<br/>
<br/>
{report}<br/>
<br/>
</div>
</div>
</body>
</html>
]],d)

end
		
-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
about=function(d)

	d=d or {}
	d.bootstrap="<a href=\"http://boot-strap.appspot.com/\">bootstrap</a>"
	d.aelua="<a href=\"http://code.google.com/p/aelua/\">aelua</a>"
	d.lua="<a href=\"http://www.lua.org/\">lua</a>"
	d.appengine="<a href=\"http://code.google.com/appengine/\">appengine</a>"
	d.wetgenes="<a href=\"http://www.wetgenes.com/\">wetgenes</a>"

	d.jill="<a href=\"http://code.google.com/p/jillcode/\">jill</a>"
	d.sputnik="<a href=\"http://sputnik.freewisdom.org/\">sputnik</a>"

	return wet_html.replace([[
<div class="aelua_about">
<br/>
<br/>
{bootstrap} is a self publishing node, designed for creators.<br/>
{bootstrap} nodes connect and share with each other.<br/>
{bootstrap} is powered by {aelua}.<br/>
<br/>
{aelua} is a {lua} core and framework compatibile with {appengine}.<br/>
{aelua} and {bootstrap} are designed and developed by {wetgenes}.<br/>
</div>
]],d)

end

		
-----------------------------------------------------------------------------
--
-- a home / tabs / next page area
--
-----------------------------------------------------------------------------
home_bar=function(d)

	d.home="<a href=\"/\">Home</a>"
		
	return wet_html.replace([[
	
<div class="aelua_home_bar">
{home}
</div>

]],d)

end

		
-----------------------------------------------------------------------------
--
-- a hello / login / logout area
--
-----------------------------------------------------------------------------
user_bar=function(d)

	if user.user then
	
		d.name="<span title=\""..user.user.email.."\" >"..(user.user.name or "?").."</span>"
	
		d.hello="Hello "..d.name.."."
		
		d.action="<a href=\""..user.logout_url(d.srv.url).."\">Logout?</a>"
	else
		d.hello="Hello Anon."
		d.action="<a href=\""..user.login_url(d.srv.url).."\">Login?</a>"
	
	end
	
	return wet_html.replace([[
	
<div class="aelua_user_bar">
{hello}
{action}
</div>

]],d)

end


			
			
		
