

local os=os
local users=require("wetgenes.aelua.users")

local wet_html=require("wetgenes.html")

local string=string
local math=math

module("html")

-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
header=function(d)

	
	if not d.title then
		local crumbs=d.srv.crumbs
		local s
		for i=1,#crumbs do local v=crumbs[i]
			if not s then s="" else s=s.." - " end
			s=s..v.title
		end
		d.title=s
	end

	return wet_html.replace([[
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
 <head>
<title>{title}</title>

<link REL="SHORTCUT ICON" HREF="/favicon.ico">

<link rel="stylesheet" type="text/css" href="/css/jnice.css" /> 
<link rel="stylesheet" type="text/css" href="/css/hoe.css" /> 

<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/jquery.jnice.js"></script>


 </head>
<body>
<div class="cont">
	<div class="header" style="background-image:url(/art/hoe.960x180.png)">
	</div>
	<div class="line"></div>
</div>

]],d)

end

-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
footer=function(d)

	if not d.time then
		d.time=math.ceil((os.clock()-d.srv.clock)*1000)/1000
	end
	
	local mods=""
	
	if d.mod_name and d.mod_link then
	
		mods=" mod <a href=\""..d.mod_link.."\">"..d.mod_name.."</a>"
	
	end

	d.report="Generated by <a href=\"http://code.google.com/p/aelua/\">aelua</a>"..mods.." in "..(d.time or 0).." Seconds."
		
	return wet_html.replace([[


<br/>
<br/>
<br/>
<div class="desc">{report}</div><br/>
<br/>
<br/>
<br/>


</body>
</html>
]],d)

end
		
-----------------------------------------------------------------------------
--
--
-----------------------------------------------------------------------------
about=function(d)

	d=d or {}
	d.hoehouse="<a href=\"http://hoe-house.appspot.com/\">hoe house</a>"
	d.whorehouse="<a href=\"http://whorehouse.naken.cc/\">whore house</a>"
	d.aelua="<a href=\"http://code.google.com/p/aelua/\">aelua</a>"
	d.lua="<a href=\"http://www.lua.org/\">lua</a>"
	d.appengine="<a href=\"http://code.google.com/appengine/\">appengine</a>"
	d.wetgenes="<a href=\"http://www.wetgenes.com/\">wetgenes</a>"

	return wet_html.replace([[
<div class="chunk">
<br/>
<br/>
{hoehouse} is a friendly hommage to {whorehouse}.<br/>
{hoehouse} is an example {aelua} app.<br/>
<br/>
{aelua} is a {lua} core and framework compatibile with {appengine}.<br/>
{aelua} and {hoehouse} are designed and developed by {wetgenes}.<br/>
</div>
]],d)

end

		
-----------------------------------------------------------------------------
--
-- a home / tabs / next page area
--
-----------------------------------------------------------------------------
home_bar=function(d)

	local crumbs=d.srv.crumbs
	local s
	for i=1,#crumbs do local v=crumbs[i]
		if not s then s="" else s=s.." / " end
		s=s.."<a href=\""..v.url.."\">"..v.link.."</a>"
	end
	d.crumbs=s
		
	return wet_html.replace([[
	
<div class="cont">
	<div class="chunk">
		<div class="chunk1">
			<div class="crum">
				<div class="crumit">{crumbs}</div>
			</div>
		</div>
		

]],d)

end

-----------------------------------------------------------------------------
--
-- a home / tabs / next page area
--
-----------------------------------------------------------------------------
hoe_menu_items=function(d)

		
	return wet_html.replace([[
	

<div class="cont">
<div class="chunk3">
<div class="chunk3it">
Basic Menu
<div class="chunk3line"></div>
</div>
<div class="clear"></div>
</div>
<div class="menu">
<div class="menu1">
<div class="menuit"><a href="work">WORK</a></div>
<div class="menuline"></div>
<div class="menup"><a href="work"><img src="/art/worka.png" width="100" height="100"></a></div>
<div class="menun">Work to gain bux, hoes and scarecrows.</div>
</div>
<div class="menu1">
<div class="menuit"><a href="shop">SHOP</a></div>
<div class="menuline"></div>
<div class="menup"><a href="shop"><img src="/art/shopa.png" width="100" height="100"></a></div>
<div class="menun">Buy what you need.<br /> <br /></div>
</div>
<div class="menu1">
<div class="menuit"><a href="profile">PROFILE</a></div>
<div class="menuline"></div>
<div class="menup"><a href="profile"><img src="/art/proa.png" width="100" height="100"></a></div>
<div class="menun">View and change how others see you.</div>
</div>
</div>
<div class="menu">
<div class="menu1">
<div class="menuit"><a href="list">LIST</a></div>
<div class="menuline"></div>
<div class="menup"><a href="list"><img src="/art/lista.png" width="100" height="100"></a></div>
<div class="menun">View the leaderboards.</div>
</div>
<div class="menu1">
<div class="menuit"><a href="fight">FIGHT</a></div>
<div class="menuline"></div>
<div class="menup"><a href="fight"><img src="/art/fighta.png" width="100" height="100"></a></div>
<div class="menun">Attack the others for fun and profit.</div>
</div>
<div class="menu1">
<div class="menuit"><a href="trade">TRADE</a></div>
<div class="menuline"></div>
<div class="menup"><a href="trade"><img src="/art/tradea.png" width="100" height="100"></a></div>
<div class="menun">Trade with the others.</div>
</div>
</div>
</div>
<div class="clear"></div>

]],d)

end
		
-----------------------------------------------------------------------------
--
-- a hello / login / logout area
--
-----------------------------------------------------------------------------
user_bar=function(d)

	if d.user then
	
		d.name="<span title=\""..d.user.cache.email.."\" >"..(d.user.cache.name or "?").."</span>"
	
		d.hello="Hello, "..d.name.."."
		
		d.action="<div class=\"log3\"><div class=\"logit\"><a href=\""..users.logout_url(d.srv.url).."\">Logout?</a></a></div>"
	else
		d.hello="Hello Anon."
		d.action="<div class=\"log2\"><div class=\"logit\"><a href=\""..users.login_url(d.srv.url).."\">Login?</a></a></div>"
	
	end
	
	return wet_html.replace([[
	
		<div class="chunk2">
			<div class="log">
				<div class="log1">
					<div class="logn">{hello}</div>
				</div>
					{action}
			</div>
		</div>
	</div>
	<div class="line"></div>
	<div class="clear"></div>
</div>

]],d)

end

-----------------------------------------------------------------------------
--
-- a basic player area for the viewer
--
-----------------------------------------------------------------------------
player_bar=function(d)

	if d.player then
			
		return wet_html.replace([[	

<div class="cont">
<div class="chunk4">
<div class="act1">
<div class="act1p">
<a href="work"><img src="/art/work.png" width="30" height="30"></a>
</div>
</div>
<div class="act1">
<div class="act1p">
<a href="shop"><img src="/art/shop.png" width="30" height="30"></a>
</div>
</div>
<div class="act1">
<div class="act1p">
<a href="pro"><img src="/art/pro.png" width="30" height="30"></a>
</div>
</div>
<div class="act1">
<div class="act1p">
<a href="list"><img src="/art/list.png" width="30" height="30"></a>
</div>
</div>
<div class="act1">
<div class="act1p">
<a href="fight"><img src="/art/fight.png" width="30" height="30"></a>
</div>
</div>
<div class="act1">
<div class="act1p">
<a href="trade"><img src="/art/trade.png" width="30" height="30"></a>
</div>
</div>
<div class="clear"></div>
</div>
</div>
		
<div class="cont">
<div class="chunk5">
<div class="hud">
<div class="hud1">
<div class="hudit">
{player.energy}
</div>
<div class="hud1">
<div class="hudp">
<img src="/art/energy.png">
</div>
<div class="hudn">
energy
</div>
</div>
</div>
<div class="hudline"></div>
<div class="hud1">
<div class="hudit">
{player.score}
</div>
<div class="hud1">
<div class="hudp">
<img src="/art/score.png">
</div>
<div class="hudn">
score
</div>
</div>
</div>
<div class="hudline"></div>
<div class="hud1">
<div class="hudit">
{player.bux}
</div>
<div class="hud1">
<div class="hudp">
<img src="/art/bux.png">
</div>
<div class="hudn">
bux
</div>
</div>
</div>
<div class="hudline"></div>
<div class="hud2">
<div class="hud2it">
{player.hoes}
</div>
<div class="hud2">
<div class="hud2p">
<img src="/art/hoes.png">
</div>
<div class="hud2n">
hoes
</div>
</div>
</div>
<div class="hudline"></div>
<div class="hud2">
<div class="hud2it">
{player.houses}
</div>
<div class="hud2">
<div class="hud2p">
<img src="/art/house.png">
</div>
<div class="hud2n">
houses
</div>
</div>
</div>
<div class="hudline"></div>
<div class="hud2">
<div class="hud2it">
{player.scarecrows}
</div>
<div class="hud2">
<div class="hud2p">
<img src="/art/scare.png">
</div>
<div class="hud2n">
scarecrows
</div>
</div>
</div>
</div>
</div>
</div>
		
]],d)

	end
	
	return wet_html.replace([[	
<div class="hoe_player_bar">
</div>
]],d)

end

-----------------------------------------------------------------------------
--
-- display a player row
--
-----------------------------------------------------------------------------
player_row=function(d)

	if d.player then
			
		return wet_html.replace([[	
<div class="hoe_player_row">
<span class="hoe_player_row_name">{player.name}</span>
<span class="hoe_player_row_score">score={player.score}</span>
<span class="hoe_player_row_bux">bux={player.bux}</span>
<span class="hoe_player_row_hoes">hoes={player.hoes}</span>
<span class="hoe_player_row_houses">houses={player.houses}</span>
<span class="hoe_player_row_scarecrows">scarecrows={player.scarecrows}</span>
<span class="hoe_player_row_shout">{player.shout}</span>
</div>
]],d)

	end
	
	return wet_html.replace([[	
<div class="hoe_player_row">
</div>
]],d)

end

-----------------------------------------------------------------------------
--
-- display most player info on thier profile
--
-----------------------------------------------------------------------------
player_base=function(d)

	if d.player then
			
		return wet_html.replace([[	
<div class="hoe_player_base">
<span class="hoe_player_base_name">{player.name}</span>
<span class="hoe_player_base_score">score={player.score}</span>
<span class="hoe_player_base_bux">bux={player.bux}</span>
<span class="hoe_player_base_hoes">hoes={player.hoes}</span>
<span class="hoe_player_base_houses">houses={player.houses}</span>
<span class="hoe_player_base_scarecrows">scarecrows={player.scarecrows}</span>
<span class="hoe_player_base_shout">{player.shout}</span>
</div>
]],d)

	end
	
	return wet_html.replace([[	
<div class="hoe_player_base">
</div>
]],d)

end
			
-----------------------------------------------------------------------------
--
-- suggest an act
--
-----------------------------------------------------------------------------
request_login=function(d)

	d.action="<a href=\""..users.login_url(d.srv.url).."\">Login</a>"
	
	return wet_html.replace([[
	
<div class="hoe_acts">
Please {action} if you wish to join this game.
</div>

]],d)

end

-----------------------------------------------------------------------------
--
-- sugest an action
--
-----------------------------------------------------------------------------
request_join=function(d)

	d.action="<a href=\""..d.H.url_base.."do/"..d.act.."\">Join</a>"
	
	return wet_html.replace([[
	
<div class="hoe_acts">
Click {action} to {action} this game.
</div>

]],d)

end

			
			
		
			
		
